Fix #1107: Update activation name
wultra/powerauth-server pull request #1109
Opened 2023-11-03 08:08 UTC by banterCZ

2023-11-03 10:52 UTC, banterCZ commented on powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/ActivationHistoryEntity.java
> +        return getClass().hashCode();
Let's not add the new field `applicationName` and return constant as suggested https://vladmihalcea.com/how-to-implement-equals-and-hashcode-using-the-jpa-entity-identifier/
If agreed, I will update our guidelines.

2023-11-03 10:57 UTC, banterCZ commented on powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/controller/api/PowerAuthControllerTest.java
> +        final List<Tuple> auditEntries = entityManager.createNativeQuery("select * from audit_log", Tuple.class).getResultList();
- [ ] Improve select to get one record only.

2023-11-07 12:21 UTC, romanstrobl approved these changes
Looks OK, I have two minor suggestions.

2023-11-07 13:04 UTC, banterCZ commented on powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/AdditionalInformation.java
> +        public static final String ACTIVATION_UPDATED = "ACTIVATION_UPDATED";
It was generic on purpose. I was open to a later extension, but I agree, let's make it more specific.

2023-11-07 16:26 UTC, zcgandcomp requested changes
Overall it is fine. I have only one remark - feel free to discuss. 

Question:
Can we name the methods and objects `updateActivationName`? And the as url use  `/activation/name/update`.

Reason:
We are not updating activation we have a specialized method for updating activation name only. So this is an analogy to the naming of method `updateActivationOtp`

2023-11-08 08:26 UTC, merged