Fix #1099: Move tests from powerauth-tests to this repo
wultra/powerauth-server pull request #1235
Opened 2024-01-03 02:20 UTC by jandusil

- Move operation tests
- Add javadoc
- Edit sql for tests

2024-01-10 11:59 UTC, banterCZ reviewed
Let's discuss whether we want to use request/response POJO instead of JSON in tests.

2024-01-10 11:59 UTC, banterCZ commented on powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/controller/api/PowerAuthControllerTest.java
> +        boolean callbackFound = false;
May we refactor into using `stream.filter(...)findAny()`?

2024-01-10 11:59 UTC, banterCZ commented on powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/controller/api/PowerAuthControllerTest.java
> +    private OperationCreateRequest createOperationCreateRequest(final boolean proximityOtp) throws Exception {
Can by `static`? Moreover, let's rename the parameter, `proximityOtp` looks like OTP value to me.
```suggestion
    private static OperationCreateRequest createOperationCreateRequest(final boolean proximityOtpEnabled) throws Exception {
```

2024-01-10 11:59 UTC, banterCZ commented on powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/controller/api/PowerAuthControllerTest.java
> +    private static String wrapInRequestObjectJson(final Object obj) throws Exception {
Personally, I do not like this method at all for several reasons. Mainly, we bypass testing of object mapper. For example, when the property name changes, the test should fail (in my opinion), but in this case it does not. May we use just string payload instead?

2024-01-10 11:59 UTC, banterCZ commented on powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/controller/api/PowerAuthControllerTest.java
> +        final String integrationId = convertMvcResultToObject(result,
🤔 Isn't it complicated to convert json to POJO? What about using something like `JsonPath.read(result.getResponse().getContentAsString(), "$.id")`

2024-01-10 11:59 UTC, banterCZ commented on powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/OperationServiceBehaviorTest.java
> +import static com.wultra.security.powerauth.client.model.enumeration.UserActionResult.APPROVAL_FAILED;
I prefer to isolate test constants from production constants. When production code changes, this test does not fail.

2024-01-15 07:36 UTC, romanstrobl requested changes
I found two issues:
- The tests are using mocks for REST API calls using `mockMvc.perform(post("..."));`.
  - This changes the functionality of tests which used to test real REST API controllers but now have been downgraded to mocking.
  - We may not catch compatibility issues, object mapping issues, security configuration problems and other issues caused by mocking instead of real REST API tests.
  - I do not see any benefit to using mocks, we can simply test the real application.
- The tests use the same application `PA_Tests` as end-to-end tests
  - I suggest to avoid using same application `PA_Tests`, because the purpose of these tests is different (component vs. end-to-end tests).
  - Why are we setting up the keypairs using SQL inserts instead of creating everything using the REST API? We miss testing this functionality. When always using same static keys we do not test the underlying cryptography properly.

To summarize, we tried to write unit tests, while these tests were originally component tests, so we downgraded the coverage quite significantly. I suggest we stick to the original idea of preparing component tests which should replace end-to-end tests which are do not require end-to-end scenarios.

2024-01-19 06:03 UTC, banterCZ commented on powerauth-java-server/pom.xml
> +            <scope>test</scope>
I believe that it could be even `runtime` scope.

2024-01-19 06:04 UTC, romanstrobl approved these changes
These changes are more inline with the original intention, thanks.

2024-01-19 06:04 UTC, romanstrobl commented on powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/controller/api/PowerAuthControllerTestConfig.java
> +     *****************************************************************
Can we avoid this style of comments with many `*` characters? It's not common in Java.

2024-01-19 06:34 UTC, banterCZ reviewed
Thanks for transforming the test from a mock into an integration one.

2024-01-19 06:34 UTC, banterCZ commented on powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/controller/api/PowerAuthControllerTest.java
> +        assertEquals(1, lookupActivationsResponse.getActivations().size());
FYI: We do not use Hamcrest yet or not heavily, but there are more elegant ways, e.g. `assertThat(collection, hasSize(1));` or some similar syntax with AssertJ (introducing AssertJ is a bigger step, but Hamcrest should be ok, if you want to).

2024-01-19 06:34 UTC, banterCZ commented on powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/controller/api/PowerAuthControllerTest.java
> +            activationIds.add(initResponse.getActivationId());
It could be nice to use `stream` -> `map`, but since we declare checked exceptions, it is not possible (or not easily at least) 😞

2024-01-19 06:34 UTC, banterCZ commented on powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/controller/api/PowerAuthControllerTest.java
> +        assertEquals(expectedErrorMessage, thrownException.getLocalizedMessage());
Duplicated line.
```suggestion
        assertEquals(expectedErrorMessage, thrownException.getLocalizedMessage());
```

2024-01-19 06:34 UTC, banterCZ commented on powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/controller/api/PowerAuthControllerTestConfig.java
> + * This class provides configuration settings and helper methods
🤔 I do not like the mixture of concept configuration and helper methods in a single class.

2024-01-19 06:34 UTC, banterCZ commented on powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/controller/api/PowerAuthControllerTestConfig.java
> +        var applicationOptional = applicationsListResponse.getApplications().stream()
May be `final`, more occurences in this class.

2024-01-19 06:34 UTC, banterCZ commented on powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/controller/api/PowerAuthControllerTestConfig.java
> +    public void setActivationId(final String activationId) {
Any reason why not to use Lombok?

2024-01-19 08:45 UTC, banterCZ approved these changes
Thanks for cleaning up the configuration class.

2024-01-19 08:53 UTC, merged