Fix #1368: Modify datatype of pa_activation.extras
wultra/powerauth-server pull request #1371
Opened 2024-03-04 13:48 UTC by jandusil

2024-03-04 14:00 UTC, banterCZ commented on docs/db/changelog/changesets/powerauth-java-server/1.7.x/20240115-add-columns-fido2.xml
> +        <modifyDataType tableName="pa_activation" columnName="extras" newDataType="varchar(4000)"/>
cc @korbelm checksum has changed

2024-03-04 14:00 UTC, banterCZ reviewed
Missing edit in `PowerAuth-Server-1.7.0.md`.

2024-03-05 06:00 UTC, banterCZ approved these changes
Looks good now.

2024-03-05 08:35 UTC, zcgandcomp requested changes

2024-03-05 08:35 UTC, zcgandcomp commented on docs/PowerAuth-Server-1.7.0.md
> +The data type for column `extras` in table `pa_activation` was changed to `VARCHAR` / `VARCHAR2` to support larger data.
```suggestion
The size of column `extras` in table `pa_activation` was increased to `4000` from `255` to support larger data.
```

2024-03-05 11:49 UTC, zcgandcomp reviewed
Looks OK.

Checksums - no need to add them. And I belive @korbelm was notified.

2024-03-05 11:49 UTC, zcgandcomp approved these changes

2024-03-05 12:01 UTC, merged