Fix #1397: Return structured device info in the operation detail resp…
wultra/powerauth-server pull request #1398
Opened 2024-03-15 00:23 UTC by jandusil

…onse

2024-03-15 00:27 UTC, jandusil commented
@petrdvorak 

Just a question - when the operation is created, the additionalData is set to `null.` Therefore, it is only after the operation is cancelled/approved/rejected when the userAgent is stored with the operation. Is that the **full** desired behaviour? Thanks
https://github.com/wultra/powerauth-server/blob/41e5750ba823dc423f7de5dd53bf9ab8d5e57b85/powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/OperationServiceBehavior.java#L192

2024-03-15 00:29 UTC, jandusil commented
Tested that the change gets propagated to PAC:

<img width="1478" alt="Screenshot 2024-03-15 at 1 21 03" src="https://github.com/wultra/powerauth-server/assets/134381434/d488ffe3-9ee5-4f5e-929b-0c5ddfcb7b95">

2024-03-15 02:17 UTC, romanstrobl approved these changes
Looks OK.

2024-03-15 06:48 UTC, petrdvorak commented
@jandusil Looks OK. The behavior you mention is correct. When the operation is created, there is no way to assign the user agent (and device info, consequently) to it immediately. At one point, I was thinking about enriching the additional data as the operation list is fetched which, in theory, is possible. But fetching can happen on multiple mobile devices, which is a problem. It would significantly complicate things and would not help with any investigations much.

2024-03-15 06:50 UTC, petrdvorak approved these changes

2024-03-15 06:53 UTC, petrdvorak requested changes
How about operation callbacks?

2024-03-18 10:07 UTC, banterCZ commented on powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/OperationServiceBehavior.java
> +    public static Optional <UserAgent.Device> parseDeviceFromUserAgent(Map<String, Object> additionalData) {
```suggestion
    public static Optional<UserAgent.Device> parseDeviceFromUserAgent(Map<String, Object> additionalData) {
```

2024-04-02 12:12 UTC, zcgandcomp requested changes
I have few remarks
- the method `convertFromEntity` enhance the  additional data with `device` object. But the data for audited are again parsed using `extendAdditionalDataWithDevice` - this is redundant.
- the method `convertFromEntity` is called frequently, but only for very few places we need to show `device` object (actually only on PAC getOperationDetail) - depends on the performance of the method - as we are playing with regexp - to do the conversion only when necessary and not all the time. (All the time is a good approach if the performance hit is small)
-

2024-04-03 09:34 UTC, jandusil commented
@zcgandcomp @petrdvorak, I've updated the solution. However, I've noticed that currently, when the methods `attemptApproveOperation`, `failApprovalOperation`, and `rejectOperation` encounter failures (i.e., they proceed to the else statement), we do not audit the UserAgent. Should we implement auditing for these scenarios as well? Thanks.

2024-04-05 06:51 UTC, petrdvorak commented
@jandusil If it is known in such a scenario, we could log it.

2024-04-05 13:07 UTC, zcgandcomp commented on powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/OperationServiceBehavior.java
> +        extendAdditionalDataWithDevice(operationDetailResponse);
But correctly we are returning the user agent when canceling the operation. This is good.

2024-04-05 15:34 UTC, zcgandcomp approved these changes
Ok from my POV it's OK.

Enriched detail is returned when relevant (detail, result of cancel).
Enriched detail is sent via callbacks.
All audit events are enriched (except create where it makes no sense)

Please if @banterCZ approves the java code itself we can merge.

2024-04-05 15:37 UTC, banterCZ approved these changes
Code style looks good.

2024-04-05 20:57 UTC, petrdvorak approved these changes
Approved

2024-04-05 23:05 UTC, merged