Fix #1538: DB migration issue (MS SQL, possible Oracle)
wultra/powerauth-server pull request #1543
Opened 2024-05-31 07:32 UTC by banterCZ

This is a fix into 1.7.x; for develop, we will make the column not-null.

2024-06-02 20:02 UTC, zcgandcomp requested changes

2024-06-02 20:02 UTC, zcgandcomp commented on powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/ActivationRecordEntity.java
> +    public void setDefaultProtocol() {
This is a fix for null values in the DB. But the null values are updated in the liquibase script.

2024-06-03 07:23 UTC, banterCZ commented
- [ ] Let's make the column _not-null_ even for backport

2024-06-03 09:29 UTC, merged

2024-06-03 09:31 UTC, romanstrobl approved these changes
Good fix.