Fix #871: Signature audit log stores the next signature value when recording verification
wultra/powerauth-server pull request #873
Opened 2023-04-03 12:13 UTC by banterCZ

2023-04-04 13:57 UTC, romanstrobl requested changes
This is much better than previous commit. However, I still have a problem with this change. 
The audit record is created before the change is propagated to database and before the signature is actually verified.

I recommend to keep the audit log write after all signature verification tasks have been completed, just use the original counter values (numeric / hash-based) before their increment. We can use some temporary DTO for this, or just keep them as temporary variables.

2023-04-06 05:35 UTC, banterCZ commented on powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/SignatureSharedServiceBehavior.java
> +        final AuditingServiceBehavior.ActivationRecordDto activationDto = createActivationDtoFrom(activation);
- [ ] I have to decide what to do with`setActivationStatus`. I prefer to audit the value before the change.

2023-04-06 06:44 UTC, banterCZ commented on powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/SignatureSharedServiceBehavior.java
> +        final AuditingServiceBehavior.ActivationRecordDto activationDto = createActivationDtoFrom(activation);
Changed in a separate commit to better review.

2023-04-11 12:18 UTC, romanstrobl approved these changes
Yes, I was expecting a solution similar to this.

2023-04-11 12:43 UTC, merged